### ISSUE TITLE
Scimitar bullet pattern

### ISSUE THREAD

**Issue by PeachTreeOath** [PeachTreeOath/Mages#13]

**Comment by PeachTreeOath** [comment]
(Can change) dashes around and leaves a wave trail of bullets behind

**Comment by MrChro** [comment]
another idea is that it could spin/slash and release a half a circle of shots that gain more speed the father away.  gives an illusion of a slash, i think?

**Comment by PeachTreeOath** [comment]
that's prbly a better idea, since I might have the sphinx boss hands fly around leaving trails
